export const data =
    [
        "Python developers think indentation is a valid substitute for proper syntax.",
        "C++ programmers are just masochists who enjoy suffering.",
        "C programmers think memory management is a personality trait.",
        "JS developers: Turning 'null' into an object since 1995.",
        "TypeScript is just JavaScript with a superiority complex.",
        "C# developers are just Java programmers who discovered Microsoft.",
        "Rust developers spend more time fighting the borrow checker than solving actual problems.",
        "SQL developers think 'JOIN' is a valid solution to all of life's problems.",
        "npm install: How to download the entire internet with one command.",
        "PHP is just a fancy way to mix HTML and SQL.",
        "Java developers write 100 lines of code to print 'Hello World'.",
        "Node.js developers believe JavaScript belongs everywhere, even on the server.",
        "CSS is not a real programming language; it's just fancy coloring.",
        "Ruby developers are just failed poets who found a new way to be obscure.",
        "COBOL programmers are like the undead - everyone thinks they're gone, but they keep coming back.",
        "Go developers are just C programmers who couldn't handle pointers.",
        "Perl code is write-only; no one can read it, not even the original author.",
        "Bash scripters believe that if you can't do it in one line, it's not worth doing.",
        "R programmers are just statisticians who got tired of Excel.",
        "Swift developers are just Objective-C programmers who finally snapped.",
        "Kotlin is what happens when Java developers have a midlife crisis.",
        "Visual Basic developers are just Excel power users with delusions of grandeur.",
        "JavaScript: Making 'this' confusing since its inception.",
        "Scala developers are Java programmers who wanted to make simple things complicated.",
        "Assembly programmers are just people who hate using keyboards efficiently.",
        "MATLAB users are engineers who think they can program.",
        "React developers believe everything should be a component, even their coffee mugs.",
        "Vue.js developers are just React refugees looking for peace.",
        "Angular developers are enterprise programmers who enjoy typing.",
        "Functional programmers are just developers who hate the 'this' keyword.",
        "Git users think 'force push' solves all merge conflicts.",
        "Agile developers believe that if you can't do it in two weeks, it's not worth doing.",
        "JavaScript equality: Because sometimes '2' == 2, and that's just fine.",
        "DevOps engineers are just sysadmins who learned to code.",
        "Full-stack developers are just developers who can't make up their minds.",
        "Machine learning engineers are just statisticians who know how to use GPUs.",
        "Data scientists are just statisticians with a MacBook Pro.",
        "Frontend developers think CSS is a programming language.",
        "Backend developers believe the command line is a valid user interface.",
        "Mobile app developers are just web developers who got sick of browser compatibility issues.",
        "Linux users spend more time customizing their desktop than actually working.",
        "JavaScript: Where undefined is not a function, but a way of life.",
        "Windows developers believe 'have you tried restarting?' is a valid debugging technique.",
        "macOS developers think different, but code the same.",
        "Docker users think everything is better in a container, even their lunch.",
        "Vim users spend more time customizing their .vimrc than actually coding.",
        "Emacs users are just operating system developers in denial.",
        "IntelliJ users believe RAM is unlimited.",
        "Visual Studio Code users think extensions solve everything.",
        "Sublime Text users are just developers who couldn't commit to Vim or Emacs.",
        "Jupyter Notebook users think code should be written like a blog post.",
        "Haskell developers believe type systems are more important than actually shipping code.",
        "Microservices architects think every function should be its own service.",
        "Monolith defenders are just architects afraid of network latency.",
        "GraphQL developers believe REST is for the weak.",
        "gRPC developers think human-readable APIs are overrated.",
        "Kubernetes users believe 'Have you tried putting it in a pod?' solves all problems.",
        "Serverless developers are just cloud engineers who hate managing servers.",
        "Terraform developers think infrastructure should be as complex as the software it runs.",
        "Web Assembly developers are just trying to make browsers the new operating systems.",
        "Electron developers believe every app should use at least 1GB of RAM.",
        "PWA developers are just web developers trying to stay relevant on mobile.",
        "Unity developers think C# is a game engine.",
        "Unreal Engine developers believe blueprints are a suitable replacement for coding.",
        "WordPress developers think they're programmers.",
        "Low-code platform users think drag-and-drop is a programming paradigm.",
        "No-code platform users are just business analysts with delusions of development grandeur.",
        "Shell script developers believe every problem can be solved with a one-liner.",
        "PowerShell developers are just Windows admins who learned to type.",
        "Regex enthusiasts believe unreadable code is a feature, not a bug.",
        "XML fans think angle brackets are the solution to everything.",
        "JSON advocates believe curly braces are superior to angle brackets.",
        "YAML enthusiasts think indentation is a valid data structure.",
        "MongoDB users believe 'schema-less' means 'problem-free'.",
        "Redis users think every problem can be solved with a key-value pair.",
        "PostgreSQL users are just MySQL users who grew up.",
        "Oracle DB users are just enterprise developers Stockholm syndromed into proprietary software.",
        "RabbitMQ users are just developers who enjoy playing message broker roulette.",
        "TensorFlow developers believe every problem can be solved with a neural network.",
        "PyTorch users are just TensorFlow developers who like Python's syntax.",
        "Scikit-learn users think every problem is a classification problem.",
        "Tableau users are just Excel users with a bigger budget.",
        "Power BI users are just Microsoft fanboys with a data fetish.",
        "SAS programmers are just statisticians trapped in the 90s.",
        "Julia programmers are just Python users who complain about speed.",
        "Dart developers are just Flutter enthusiasts who forgot about the web.",
        "Lua programmers are game developers who couldn't handle C++.",
        "F# programmers are C# developers who wanted to feel smarter.",
        "Groovy programmers are Java developers who wanted to be cool but not too cool.",
        "Typescript developers are just JavaScript programmers with trust issues."
        ,
        "Embedded systems programmers are just C developers with a soldering iron.",
        "Game developers are just masochists who enjoy crunch time.",
        "Database administrators think every problem can be solved with another index.",
        "UI designers are just artists who couldn't make it in the real world.",
        "UX designers are just psychologists who couldn't get a real degree.",
        "QA engineers are developers who enjoy breaking things more than building them.",
        "Cybersecurity experts are just paranoid developers.",
        "Cloud architects are just developers who enjoy drawing boxes and arrows.",
        "Blockchain developers are just cryptographers with a gambling problem.",
        "IoT developers are just embedded programmers who discovered Wi-Fi."
    ]
