export const SCIENTISTS = [
  {
    first: "Albert",
    last: "Einstein",
    gender: "Male",
    nationality: "German",
    birth: 1879,
    passed: 1955,
    image: "./img/einstein.jpeg",
  },
  {
    first: "Ernest",
    last: "Rutherford",
    gender: "Male",
    nationality: "New Zealander",
    birth: 1871,
    passed: 1937,
    image: "./img/rutherford.jpeg",
  },
  {
    first: "Isaac",
    last: "Newton",
    gender: "Male",
    nationality: "English",
    birth: 1643,
    passed: 1727,
    image: "./img/newton.jpeg",
  },
  {
    first: "Galileo",
    last: "Galilei",
    gender: "Male",
    nationality: "Italian",
    birth: 1564,
    passed: 1642,
    image: "./img/galilei.jpeg",
  },
  {
    first: "Nikola",
    last: "Tesla",
    gender: "Male",
    nationality: "Serbian-American",
    birth: 1856,
    passed: 1943,
    image: "./img/tesla.jpeg",
  },
  {
    first: "Marie",
    last: "Curie",
    gender: "Female",
    nationality: "Polish-French",
    birth: 1867,
    passed: 1934,
    image: "./img/curie.jpeg",
  },
  {
    first: "Stephen",
    last: "Hawking",
    gender: "Male",
    nationality: "English",
    birth: 1942,
    passed: 2018,
    image: "./img/hawking.jpeg",
  },
  {
    first: "Richard",
    last: "Feynman",
    gender: "Male",
    nationality: "American",
    birth: 1918,
    passed: 1988,
    image: "./img/feynman.jpeg",
  },
  {
    first: "Rosalind",
    last: "Franklin",
    gender: "Female",
    nationality: "English",
    birth: 1920,
    passed: 1958,
    image: "./img/rosalind.jpeg",
  },
  {
    first: "Niels",
    last: "Bohr",
    gender: "Male",
    nationality: "Danish",
    birth: 1885,
    passed: 1962,
    image: "./img/bohr.jpeg",
  },
  {
    first: "Johannes",
    last: "Kepler",
    gender: "Male",
    nationality: "German",
    birth: 1571,
    passed: 1630,
    image: "./img/kepler.jpeg",
  },
  {
    first: "Nicolaus",
    last: "Copernicus",
    gender: "Male",
    nationality: "Polish",
    birth: 1473,
    passed: 1543,
    image: "./img/copernicus.jpeg",
  },
  {
    first: "Max",
    last: "Planck",
    gender: "Male",
    nationality: "German",
    birth: 1858,
    passed: 1947,
    image: "./img/planck.jpeg",
  },
  {
    first: "Katherine",
    last: "Blodgett",
    gender: "Female",
    nationality: "American",
    birth: 1898,
    passed: 1979,
    image: "./img/kath.jpeg",
  },
  {
    first: "Ada",
    last: "Lovelace",
    gender: "Female",
    nationality: "English",
    birth: 1815,
    passed: 1852,
    image: "./img/ada.jpeg",
  },
  {
    first: "Sarah E.",
    last: "Goode",
    gender: "Female",
    nationality: "American",
    birth: 1855,
    passed: 1905,
    image: "./img/goode.jpeg",
  },
  {
    first: "Lise",
    last: "Meitner",
    gender: "Female",
    nationality: "Austrian-Swedish",
    birth: 1878,
    passed: 1968,
    image: "./img/meitner.jpeg",
  },
  {
    first: "Hanna",
    last: "Hammarström",
    gender: "Female",
    nationality: "Swedish",
    birth: 1829,
    passed: 1909,
    image: "./img/hanna.jpeg",
  },
];

export const people = [
  "Bernhard, Sandra",
  "Bethea, Erin",
  "Becker, Carl",
  "Bentsen, Lloyd",
  "Beckett, Samuel",
  "Blake, William",
  "Berger, Ric",
  "Beddoes, Mick",
  "Beethoven, Ludwig",
  "Belloc, Hilaire",
  "Begin, Menachem",
  "Bellow, Saul",
  "Benchley, Robert",
  "Blair, Robert",
  "Benenson, Peter",
  "Benjamin, Walter",
  "Berlin, Irving",
  "Benn, Tony",
  "Benson, Leana",
  "Bent, Silas",
  "Berle, Milton",
  "Berry, Halle",
  "Biko, Steve",
  "Beck, Glenn",
  "Bergman, Ingmar",
  "Black, Elk",
  "Berio, Luciano",
  "Berne, Eric",
  "Berra, Yogi",
  "Berry, Wendell",
  "Bevan, Aneurin",
  "Ben-Gurion, David",
  "Bevel, Ken",
  "Biden, Joseph",
  "Bennington, Chester",
  "Bierce, Ambrose",
  "Billings, Josh",
  "Birrell, Augustine",
  "Blair, Tony",
  "Beecher, Henry",
  "Biondo, Frank",
];

export const duplicates = [
  "car",
  "car",
  "truck",
  "truck",
  "bike",
  "walk",
  "car",
  "van",
  "bike",
  "walk",
  "car",
  "van",
  "car",
  "truck",
];
